<Project ToolsVersion="15.0">
  <!--
    To update the version of Uno, you should instead update the Sdk version in the global.json file.

    See https://aka.platform.uno/using-uno-sdk for more information.
  -->
  <ItemGroup>
    <PackageVersion Include="JetBrains.Annotations" Version="2025.2.4" />
    <PackageVersion Include="Microsoft.SourceLink.GitHub" Version="10.0.300" />
    <PackageVersion Include="MimeMapping" Version="4.0.0" />
    <PackageVersion Include="P42.Uno.WebView2Extensions" Version="$(UnoVersion)" />

    <!-- Uno.Sdk 6.5.36 Warning fix -->
    <PackageVersion Include="System.Security.Cryptography.Xml" Version="10.0.8" />
    <PackageVersion Include="Tmds.DBus.Protocol" Version="0.21.3" />

  </ItemGroup>
</Project>