#!/bin/zsh

./winWipe

/cygdrive/c/Program\ Files/Microsoft\ Visual\ Studio/2022/Community/MSBuild/Current/Bin/MSBuild.exe /r /p:Configuration=Release -verbosity:minimal P42.Uno.WebView2Extensions/P42.Uno.WebView2Extensions.Native.csproj
# /cygdrive/c/Program\ Files/Microsoft\ Visual\ Studio/2022/Community/MSBuild/Current/Bin/MSBuild.exe /r /p:Configuration=Release -verbosity:minimal P42.Uno.HtmlExtensions
# /cygdrive/c/Program\ Files/Microsoft\ Visual\ Studio/2022/Community/MSBuild/Current/Bin/MSBuild.exe /r /p:Configuration=Release -verbosity:minimal P42.Uno.MarkdownExtensions

/cygdrive/c/Program\ Files/Microsoft\ Visual\ Studio/2022/Community/MSBuild/Current/Bin/MSBuild.exe /r /p:Configuration=Release -verbosity:minimal P42.Uno.WebView2Extensions/P42.Uno.WebView2Extensions.Skia.csproj
# /cygdrive/c/Program\ Files/Microsoft\ Visual\ Studio/2022/Community/MSBuild/Current/Bin/MSBuild.exe /r /p:Configuration=Release -verbosity:minimal P42.Uno.HtmlExtensions
# /cygdrive/c/Program\ Files/Microsoft\ Visual\ Studio/2022/Community/MSBuild/Current/Bin/MSBuild.exe /r /p:Configuration=Release -verbosity:minimal P42.Uno.MarkdownExtensions

/cygdrive/c/Program\ Files/Microsoft\ Visual\ Studio/2022/Community/MSBuild/Current/Bin/MSBuild.exe /r /p:Configuration=Release   -verbosity:minimal P42.Uno.WebView2Extensions/P42.Uno.WebView2Extensions.csproj
