<Project ToolsVersion="15.0">


  <ItemGroup>
    <PackageReference Include="P42.Uno.WebView2Extensions" />
  </ItemGroup>


  <ItemGroup>
    <EmbeddedResource Include="WebAssembly\WasmScripts\P42_Uno_MarkdownExtensions_JavaScript.js" />
  </ItemGroup>


  <!-- Uno.Sdk 6.5.36 Warning fix -->
  <ItemGroup>
    <PackageReference Include="Tmds.DBus.Protocol" />
  </ItemGroup>


</Project>
